version: "3"
services:
  app:
    build:
      context: "../../image"
      dockerfile: Dockerfile
    image: jonathanpaella/agentlaunchpadstarterkit:latest
    container_name: agent-tee-phala
    environment:
      - PORT=4000
      - DSTACK_SIMULATOR_ENDPOINT=${DSTACK_SIMULATOR_ENDPOINT:-}
    ports:
      - 4000:4000
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: always
